name: ChatGPT Review

on: [pull_request]


jobs:
  chatgpt-review:
    name: ChatGPT Review
    runs-on: ubuntu-latest
    steps:
    - uses: seandong/ChatGPT-Reviewer@main
      name: ChatGPT Review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      # Optional configurations:
      # with:
      #   model: "gpt-3.5-turbo"
      #   temperature: 0.2
      #   review_per_file: true
      #   comment_per_file: true
